[package]
name = "ferrisshare"
version = "0.0.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
clap = "4.5.50"
tokio = { version = "1", features = ["net", "rt-multi-thread", "rt", "fs", "io-util", "sync", "macros"] }
